version: "3"
services:
  mysql_db:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql/data 