CREATE DATABASE logs;

USE logs;

CREATE TABLE logs
  (
     upstream_uri                                      TEXT,
     client_ip                                         VARCHAR(15),
     started_at                                        DATETIME,
     request_method                                    TEXT,
     request_uri                                       TEXT,
     request_url                                       TEXT,
     request_size                                      INT,
     request_querystring                               JSON,
     request_headers_accept                            TEXT,
     request_headers_host                              TEXT,
     request_headers_user_agent                        TEXT,
     response_status                                   INT,
     response_size                                     INT,
     response_headers_content_length                   INT,
     response_headers_via                              TEXT,
     response_headers_connection                       TEXT,
     response_headers_access_control_allow_credentials TEXT,
     response_headers_content_type                     TEXT,
     response_headers_server                           TEXT,
     response_headers_access_control_allow_origin      TEXT,
     authenticated_entity_consumer_id_uuid             TEXT,
     route_created_at                                  DATETIME,
     route_hosts                                       TEXT,
     route_id                                          TEXT,
     route_methods                                     JSON,
     route_paths                                       JSON,
     route_preserve_host                               BOOLEAN,
     route_protocols                                   JSON,
     route_regex_priority                              INT,
     route_service_id                                  TEXT,
     route_strip_path                                  BOOLEAN,
     route_updated_at                                  DATETIME,
     service_connect_timeout                           INT,
     service_created_at                                DATETIME,
     service_host                                      TEXT,
     service_id                                        TEXT,
     service_name                                      TEXT,
     service_path                                      TEXT,
     service_port                                      INT,
     service_protocol                                  TEXT,
     service_read_timeout                              INT,
     service_retries                                   INT,
     service_updated_at                                DATETIME,
     service_write_timeout                             INT,
     latencies_proxy                                   INT,
     latencies_kong                                    INT,
     latencies_request                                 INT,
     created_at                                        DATETIME DEFAULT
     CURRENT_TIMESTAMP
  );